---
- name: create faucet account
  when: not multi_node_docker
  shell: |
    {{chain_bin}} keys add faucet --home {{chain_home}} --keyring-backend {{node_keyring}} --output json
    {{chain_bin}} add-genesis-account faucet 1000000000000{{ chain_denom }} --home {{chain_home}} --keyring-backend="{{node_keyring}}"
  register: create_faucet_output
  become: yes

- name: save faucet name, address, and mnemonic
  when: not multi_node_docker
  copy:
    content: "{{create_faucet_output.stderr}}"
    dest: "{{chain_home}}/faucet.json"
  become: yes

- name: collect faucet address
  when: not multi_node_docker
  shell: |
    jq -r '.address' {{chain_home}}/faucet.json
  register: faucet_address
  become: yes

- name: set faucet address
  when: not multi_node_docker
  set_fact:
    faucet_address: "{{ faucet_address.stdout }}"
